### ISSUE TITLE
Windows spots this as trojan/malware

### ISSUE THREAD

**Issue by aconfusedcoderongithub** [Cantersoft/YTPMVE#22]
Recently i wanted to download this and i got a popup saying that YTPMVE contains **_trojan/malware_**, so i immediately deleted it, can you please update this with a **_trojan-free/malware-free version and delete the old release?_**

**Comment by Cantersoft** [comment]
That message appears because the release compiles `YTPMVE.py` into `YTPMVE.exe` on download so that it can be used without installing Python. It is uncommon to compile Python code, which is why Windows flags this. If you don't want to download the executable, you can instead install Python and the Python mido module, download YTPMVE from `Code` > `Download ZIP` on the main repository page instead of on the releases page, open `YTPMVE.cs` and change the variable `string engineFilePath` to `pyFilePath`, and then run the install batch script.
