### ISSUE TITLE
Exception thrown by method called, but different details than Shalupon's issue.

### ISSUE THREAD

**Issue by jackyllSnoff** [Cantersoft/YTPMVE#30]
Installed the script with the .bat, haven't gotten it to work once. This is the error message that shows everytime. I'm using VP14 on Windows 11. What does this mean, and how can I fix it? (P.S, I would install Vegas Pro 17, but I'm running low on disk space.)
![Screenshot 2024-10-14 135729](https://github.com/user-attachments/assets/2f874738-c9b5-4051-b779-964baa3f1db0)

**Comment by Cantersoft** [comment]
It looks like your OS believes the `Newtonsoft.Json.dll` library file is unsafe because it came from a remote source (i.e., downloaded from the internet). It's hard to troubleshoot this issue without more specific details, so if you wouldn't mind messaging me on Discord (@cantersoft), I could help you fix the problem a lot quicker.

That being said, one possible solution to try right away is **right-click on `Newtonsoft.Json.dll` > Properties > Unblock**. Let me know if that works.

**Comment by jackyllSnoff** [comment]
Unblocking the .dll worked, thanks.
